use_frameworks!

platform :ios, '9.0'

target 'OYKeyboardScrollView_Example' do
  pod 'OYKeyboardScrollView', :path => '../'

  target 'OYKeyboardScrollView_Tests' do
    inherit! :search_paths

    
  end
end
